### ISSUE TITLE
Cannot select files when importing

### ISSUE THREAD

**Issue by sith-on-mars** [flathub/io.ente.auth#10]
After I opened import codes, pressing select files didn't do anything, regardless of input sources.

**Comment by mostafaroshdy1** [comment]
this issue is making the app unusable for me, i am trying to migrate from aegis to ente auth

**Comment by conan747** [comment]
I think this is because the flatpak version doesn't have file system access. From flathub:

```
No file system access
Cannot access the file system at all
```

**Comment by kolon0** [comment]
> I think this is because the flatpak version doesn't have file system access. From [flathub](https://flathub.org/apps/io.ente.auth):
> 
> ```
> No file system access
> Cannot access the file system at all
> ```

It should use portals instead. But it don't...

**Comment by kolon0** [comment]
It seems like Zenity is missing from this Flatpak. I added this to the YAML file:
```
- name: zenity
  buildsystem: meson
  sources:
    - type: archive
      url: https://download.gnome.org/sources/zenity/4.1/zenity-4.1.90.tar.xz
      sha256: bf3679c6205ff48dcebd1e1dff3a3a4a6a0b3a53e1cbc3b098a9ec0b62bd7236
```
Then I tried to build it, but it failed with an "insufficient memory" error (I have 16GB of RAM). The Linux kernel killed the process, so I couldn't test it. I don't know how to test it, but the Flatpak should use portals—it just doesn't use them at all. Can someone enlighten me?
